# Generated by Django 2.2.6 on 2022-07-26 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20220726_2337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='posts/', verbose_name='Картинра'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(help_text={'create': 'Напишите', 'edit': 'Редактируйте'}),
        ),
    ]
